/*
 * Generated by tools/gen-font.py -- do not edit by hand.
 *
 * Source face: DejaVuSansMono.ttf at 13px
 * Cell: 8x16, coverage of ASCII 32..126
 */
#ifndef FUNNYOS_FONT8X16_H
#define FUNNYOS_FONT8X16_H

#include <stdint.h>

#define FONT8X16_WIDTH   8
#define FONT8X16_HEIGHT  16
#define FONT8X16_FIRST   32
#define FONT8X16_LAST    126

/* One row per byte, MSB is the leftmost pixel. */
extern const uint8_t g_font8x16[FONT8X16_LAST - FONT8X16_FIRST + 1][FONT8X16_HEIGHT];

#endif /* FUNNYOS_FONT8X16_H */
