#!/usr/bin/env python3
"""Turn a flat binary into a C source file that defines it as an array.

    bin2c.py <input> <symbol> <output> [memory-size]

Emits two symbols:

    const unsigned char  <symbol>[]           the bytes
    const unsigned long  <symbol>_size        the length

and a third, always:

    const unsigned long  <symbol>_mem_size    the memory to build for it

The last two are the loader's pair of sizes, and they are different
numbers whenever the program asks for a region longer than its own image.
See the note on _image_end in user/link.ld for where the second number
comes from and why it cannot be read out of the image.

When the fourth argument is omitted the memory size is taken to be the
image length, which is the right answer for a program that declares no
such region -- and keeps the older three-argument call meaning exactly
what it always did.

The kernel embeds its user programs this way rather than linking them in
as objects. A user program is not kernel code -- it is compiled with a
different code model, linked against a different linker script, and laid
out for a different address -- so the only thing the two sides need to
agree on is a blob of bytes, how long it is, and how much memory to put
it in, which is exactly what a byte array and two counts are.

Twelve bytes per line: wide enough not to bloat the file, narrow enough to
read an offset off the left margin when a disassembly needs to be matched
against it.
"""

import sys

BYTES_PER_LINE = 12


def main() -> int:
    if len(sys.argv) not in (4, 5):
        print(__doc__.strip(), file=sys.stderr)
        return 2

    source, symbol, destination = sys.argv[1:4]

    with open(source, "rb") as handle:
        data = handle.read()

    memory_size = len(data)
    if len(sys.argv) == 5:
        try:
            memory_size = int(sys.argv[4], 0)
        except ValueError:
            print("bin2c.py: memory size must be a number, got %r"
                  % sys.argv[4], file=sys.stderr)
            return 2

    # Not a theoretical check: a memory size below the image length would
    # be a program whose own code does not fit in the memory it asks for.
    # The loader refuses it too, but refusing it here names the Makefile
    # line that computed the number, which is where the mistake is.
    if memory_size < len(data):
        print("bin2c.py: memory size %d is smaller than the %d-byte image "
              "%s" % (memory_size, len(data), source), file=sys.stderr)
        return 2

    with open(destination, "w", newline="\n") as out:
        out.write("/* Generated by tools/bin2c.py from %s -- do not edit. */\n"
                  % source.split("/")[-1])
        out.write("\n")
        out.write("const unsigned char %s[] = {\n" % symbol)

        for offset in range(0, len(data), BYTES_PER_LINE):
            chunk = data[offset:offset + BYTES_PER_LINE]
            body = " ".join("0x%02x," % byte for byte in chunk)
            out.write("    %-62s/* %06x */\n" % (body, offset))

        out.write("};\n")
        out.write("\n")
        out.write("const unsigned long %s_size = %dUL;\n" % (symbol, len(data)))
        out.write("const unsigned long %s_mem_size = %dUL;\n"
                  % (symbol, memory_size))

    return 0


if __name__ == "__main__":
    sys.exit(main())
