#!/usr/bin/env python3
"""Turn a flat binary into a C source file that defines it as an array.

    bin2c.py <input> <symbol> <output>

Emits two symbols:

    const unsigned char  <symbol>[]           the bytes
    const unsigned long  <symbol>_size        the length

The kernel embeds its user programs this way rather than linking them in
as objects. A user program is not kernel code -- it is compiled with a
different code model, linked against a different linker script, and laid
out for a different address -- so the only thing the two sides need to
agree on is a blob of bytes and its length, which is exactly what a byte
array and a count are.

Twelve bytes per line: wide enough not to bloat the file, narrow enough to
read an offset off the left margin when a disassembly needs to be matched
against it.
"""

import sys

BYTES_PER_LINE = 12


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    source, symbol, destination = sys.argv[1:4]

    with open(source, "rb") as handle:
        data = handle.read()

    with open(destination, "w", newline="\n") as out:
        out.write("/* Generated by tools/bin2c.py from %s -- do not edit. */\n"
                  % source.split("/")[-1])
        out.write("\n")
        out.write("const unsigned char %s[] = {\n" % symbol)

        for offset in range(0, len(data), BYTES_PER_LINE):
            chunk = data[offset:offset + BYTES_PER_LINE]
            body = " ".join("0x%02x," % byte for byte in chunk)
            out.write("    %-62s/* %06x */\n" % (body, offset))

        out.write("};\n")
        out.write("\n")
        out.write("const unsigned long %s_size = %dUL;\n" % (symbol, len(data)))

    return 0


if __name__ == "__main__":
    sys.exit(main())
