#!/usr/bin/env python3
"""
Generate the kernel's 8x16 bitmap font from a TrueType face.

Why generate rather than hand-write: a hand-authored font is thousands of
bytes of bitmap data that cannot be verified by reading it. Rasterising a
real typeface and committing the output means the glyphs are correct by
construction, and the generator documents exactly where they came from.

The generated file is checked in (kernel/console/font8x16.c) so that a
normal build has no Python or font dependency. Re-run this script only
when changing the cell size or the source face.

Usage:
    python3 tools/gen-font.py [--preview]
"""

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# --- Cell and coverage -------------------------------------------------
CELL_W, CELL_H = 8, 16
FIRST_CHAR, LAST_CHAR = 32, 126      # printable ASCII, space through ~

# DejaVu Sans Mono metrics are metrics-per-em 2048 with ascent+descent
# totalling ~1.16 em, so a pixel size of 13 keeps the glyph inside 16 rows.
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FONT_SIZE = 13

THRESHOLD = 96        # coverage above this becomes a lit pixel

OUT_C = Path("kernel/console/font8x16.c")
OUT_H = Path("kernel/include/funnyos/font8x16.h")


def render_glyph(font, ch: str) -> list[int]:
    """Rasterise one character into CELL_H rows of CELL_W bits."""
    img = Image.new("L", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)

    ascent, descent = font.getmetrics()
    # Vertically centre the ascent+descent box, keeping a shared baseline
    # across all glyphs so text does not jitter row to row.
    baseline = (CELL_H - (ascent + descent)) // 2 + ascent

    advance = font.getlength(ch)
    x = (CELL_W - advance) / 2

    draw.text((x, baseline), ch, font=font, fill=255, anchor="ls")

    rows = []
    px = img.load()
    for y in range(CELL_H):
        bits = 0
        for x_ in range(CELL_W):
            if px[x_, y] >= THRESHOLD:
                bits |= 0x80 >> x_          # MSB is the leftmost pixel
        rows.append(bits)
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true",
                    help="print rendered glyphs as ASCII art and exit")
    args = ap.parse_args()

    if not Path(FONT_PATH).exists():
        print(f"error: font not found: {FONT_PATH}", file=sys.stderr)
        print("install with: apt-get install fonts-dejavu-core", file=sys.stderr)
        return 1

    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    if args.preview:
        for ch in "AMg0#/|":
            print(f"--- {ch!r} ---")
            for row in render_glyph(font, ch):
                print("".join("#" if row & (0x80 >> b) else "." for b in range(CELL_W)))
        return 0

    glyphs = [(chr(c), render_glyph(font, chr(c))) for c in range(FIRST_CHAR, LAST_CHAR + 1)]

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_C.parent.mkdir(parents=True, exist_ok=True)

    with OUT_H.open("w") as f:
        f.write(f"""/*
 * Generated by tools/gen-font.py -- do not edit by hand.
 *
 * Source face: {Path(FONT_PATH).name} at {FONT_SIZE}px
 * Cell: {CELL_W}x{CELL_H}, coverage of ASCII {FIRST_CHAR}..{LAST_CHAR}
 */
#ifndef FUNNYOS_FONT8X16_H
#define FUNNYOS_FONT8X16_H

#include <stdint.h>

#define FONT8X16_WIDTH   {CELL_W}
#define FONT8X16_HEIGHT  {CELL_H}
#define FONT8X16_FIRST   {FIRST_CHAR}
#define FONT8X16_LAST    {LAST_CHAR}

/* One row per byte, MSB is the leftmost pixel. */
extern const uint8_t g_font8x16[FONT8X16_LAST - FONT8X16_FIRST + 1][FONT8X16_HEIGHT];

#endif /* FUNNYOS_FONT8X16_H */
""")

    with OUT_C.open("w") as f:
        f.write(f"""/*
 * Generated by tools/gen-font.py -- do not edit by hand.
 *
 * Source face: {Path(FONT_PATH).name} at {FONT_SIZE}px
 * Cell: {CELL_W}x{CELL_H}, coverage of ASCII {FIRST_CHAR}..{LAST_CHAR}
 */
#include <funnyos/font8x16.h>

const uint8_t g_font8x16[FONT8X16_LAST - FONT8X16_FIRST + 1][FONT8X16_HEIGHT] = {{
""")
        for ch, rows in glyphs:
            label = ch if ch != "\\" else "\\\\"
            f.write(f"    /* {ord(ch):3d} {label!r} */ {{ ")
            f.write(", ".join(f"0x{r:02x}" for r in rows))
            f.write(" },\n")
        f.write("};\n")

    print(f"wrote {OUT_C} and {OUT_H} ({len(glyphs)} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
