#!/bin/bash
#
# User program test.
#
# Four boots of the same image, with the kernel command line as the only
# difference. Each one exercises a different way for control to leave a
# process, and each has its own way of going wrong:
#
#   1. Normally. The shell starts in Ring 3 and stays there. Checks the
#      load path, the iretq into Ring 3, and the system call interface --
#      and the memory the kernel built for the program, which is now
#      larger than the image embedded in the kernel and is mapped, zeroed
#      and made writable by the loader rather than carried through the
#      image. Three assertions, because those are three different ways to
#      get it wrong; the mapped one is really the absence of a fault, so
#      it shows up below as "the shell did not fault".
#
#   2. With `selftest=userfault`. The program writes to an address it has
#      no mapping for. This is the one that checks the claim FunnyOS
#      makes against DOS: a program that goes wrong stops being a
#      program, not a machine. The kernel must report the fault, end that
#      process and carry on -- not panic, and certainly not triple fault.
#
#   3. With `selftest=userexit`. The program returns a known non-zero
#      code. Checks the other way a process ends, and that the code
#      actually travels back rather than the kernel reporting whatever it
#      had to hand.
#
#   4. With `selftest=fputest`. The program does exact floating point
#      arithmetic and checks the answer, which is proof that the
#      arrangement works: SSE is enabled, x87 works, and a program built
#      to use them runs instead of faulting.
#
#      It is NOT proof that the kernel's handlers leave vector registers
#      alone, and the program's own comment says as much. That was
#      measured rather than assumed: the loops ask the clock every round,
#      so a tick that falls inside one lands in a system call, with the
#      kernel on its own stack and no program behind it -- this boot
#      reports 33 ticks in total and none of them from Ring 3. (The
#      "Stack check" line below is where that number comes from, and it
#      is why that line exists.) The claim is settled statically instead,
#      by tools/check-no-vector-regs.sh, which disassembles the linked
#      kernel and fails the build if a single vector register appears.
#
#   5. With `selftest=spawn`. The program asks the kernel to run another
#      program and waits for its exit code. This is the one that checks
#      what a nested run has to give back: the address space, the current
#      process, and -- the one that bites -- the kernel stack an interrupt
#      lands on. Both sides spin long enough for timer ticks to arrive in
#      Ring 3, and the kernel says afterwards where those frames went. The
#      assertion that matters is the parent's spin *after* the child is
#      gone, because that is where a stack that was not given back would
#      still be the child's, and freed.
#
# Five boots rather than one because a process only ends once, and the
# command line is the only thing that can differ between them.
#
# Usage: bash tools/run-user-test.sh [ISO path] [bios|uefi]
#
set -u

PROJ="/mnt/c/FunnyOS"
cd "$PROJ"

BUILD_DIR="${FUNYOS_BUILD_DIR:-/var/tmp/funyos-build}"
ISO="${1:-$BUILD_DIR/funyos.iso}"
MODE="${2:-bios}"

WORK="$BUILD_DIR/user-test"
TIMEOUT_SECS="${QEMU_TIMEOUT:-20}"

FAILED=0
CHECKS=0

if [ ! -f "$ISO" ]; then
    echo "ERROR: ISO not found: $ISO" >&2
    echo "       Run make first." >&2
    exit 1
fi

if [ ! -d "$BUILD_DIR/iso_root" ]; then
    echo "ERROR: $BUILD_DIR/iso_root missing; run make first." >&2
    exit 1
fi

mkdir -p "$WORK"

if [ -e /dev/kvm ] && [ -w /dev/kvm ]; then
    ACCEL="-enable-kvm -cpu host"
    echo "  Acceleration : KVM (hardware)"
else
    ACCEL="-cpu max"
    echo "  Acceleration : TCG (software emulation, slow)"
fi

if [ "$MODE" = "uefi" ]; then
    cp /usr/share/OVMF/OVMF_VARS_4M.fd "$WORK/vars.fd"
    FIRMWARE_ARGS="-M q35 \
        -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,unit=1,file=$WORK/vars.fd"
    BOOT_ARGS=""
else
    FIRMWARE_ARGS=""
    BOOT_ARGS="-boot d"
fi

# ---------------------------------------------------------------- images
#
# Extra images with a different kernel command line, built here rather
# than through the Makefile for the same reason the fault-injection test
# does it: the shipping image should not carry paths that make a program
# fault or exit on its own.
build_image() {
    local cmdline="$1" output="$2"

    rm -rf "$WORK/root"
    cp -r "$BUILD_DIR/iso_root" "$WORK/root"

    cat > "$WORK/root/boot/limine.conf" <<EOF
# Generated by tools/run-user-test.sh -- $cmdline run.
timeout: 0
serial: yes
serial_baudrate: 115200

/FunnyOS ($cmdline)
    protocol: limine
    kernel_path: fslabel(FUNNYOS):/boot/funyos.elf
    resolution: 1024x768x32
    cmdline: $cmdline
EOF

    xorriso -as mkisofs -R -r -J \
        -V "FUNNYOS" \
        -b boot/limine-bios-cd.bin \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        --efi-boot boot/limine-uefi-cd.bin \
        -efi-boot-part --efi-boot-image \
        "$WORK/root" -o "$output" >/dev/null 2>&1
}

FAULT_ISO="$WORK/funyos-userfault.iso"
EXIT_ISO="$WORK/funyos-userexit.iso"
FPU_ISO="$WORK/funyos-fputest.iso"
SPAWN_ISO="$WORK/funyos-spawn.iso"

build_image "selftest=userfault" "$FAULT_ISO"
build_image "selftest=userexit"  "$EXIT_ISO"
build_image "selftest=fputest"   "$FPU_ISO"
build_image "selftest=spawn"     "$SPAWN_ISO"

# ---------------------------------------------------------------- boot

boot() {
    local image="$1" log="$2"
    rm -f "$log"

    # shellcheck disable=SC2086
    timeout "$TIMEOUT_SECS" qemu-system-x86_64 \
        -m 512 -cdrom "$image" $BOOT_ARGS \
        -serial "file:$log" -display none -no-reboot \
        $FIRMWARE_ARGS $ACCEL >/dev/null 2>&1
}

expect_present() {
    CHECKS=$((CHECKS + 1))
    if grep -qF "$1" "$3" 2>/dev/null; then
        printf '  [ok]   %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    fi
}

expect_absent() {
    CHECKS=$((CHECKS + 1))
    if grep -qF "$1" "$3" 2>/dev/null; then
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    else
        printf '  [ok]   %s\n' "$2"
    fi
}

show() {
    printf '\n=================== %s ===================\n' "$1"
    sed -n '/\[user program\]/,$p' "$2" 2>/dev/null | cat -s
    printf '=================================================\n\n'
}

# ------------------------------------------------------------ run 1

LOG1="$WORK/serial-normal-$MODE.log"
echo "  Boot 1: normal startup ($MODE)"
boot "$ISO" "$LOG1"
show "normal startup" "$LOG1"

echo "Assertions (normal startup, $MODE):"
expect_present "Image          :"            "user image embedded in the kernel" "$LOG1"
expect_present "FunnyCOM 0.1"                "shell started in Ring 3"           "$LOG1"
expect_present "F:\\>"                       "shell reached its prompt"          "$LOG1"
expect_absent  "PANIC"                       "no kernel panic"                   "$LOG1"
expect_absent  "program fault"               "the shell did not fault"           "$LOG1"
expect_absent  "CPU EXCEPTION"               "no CPU exception"                  "$LOG1"

# The program's memory is larger than the image, and the part of it that
# is not in the image is the loader's to create. All three have to hold
# and they fail differently: a page that was never mapped faults before
# these lines are reached (which is what the two assertions above catch),
# one that was mapped and not cleared reads as somebody's leftovers, and
# one that is there and read-only fails on the first write.
expect_present "Tail mapped    : yes"        "the loader built the program's tail"  "$LOG1"
expect_present "Tail zeroed    : yes"        "every byte of it was cleared"        "$LOG1"
expect_present "Tail writable  : yes"        "and the program can write to it"     "$LOG1"

# ------------------------------------------------------------ run 2

LOG2="$WORK/serial-fault-$MODE.log"
echo
echo "  Boot 2: deliberate program fault ($MODE)"
boot "$FAULT_ISO" "$LOG2"
show "program fault" "$LOG2"

echo "Assertions (program fault, $MODE):"
expect_present "Startup arg    : 1"          "the fault mode reached the program"        "$LOG2"
expect_present "program fault"               "kernel recognised the fault as a program's" "$LOG2"
expect_present "#PF Page Fault"              "fault identified as a page fault"          "$LOG2"
expect_present "faulting address"            "the faulting address was reported"         "$LOG2"
expect_present "ending the process"          "kernel said what it would do about it"     "$LOG2"
expect_present "killed by fault 14"          "process ended with the fault as its code"  "$LOG2"

# The claim being tested. A panic here would mean a program with a wild
# pointer takes the machine down -- exactly what DOS did, and exactly what
# this system exists to stop doing.
expect_absent  "PANIC"                       "the kernel did not panic"                  "$LOG2"
expect_absent  "CPU EXCEPTION"               "the fault was not treated as the kernel's" "$LOG2"
expect_present "nothing left to run"         "the kernel carried on after the program died" "$LOG2"

# ------------------------------------------------------------ run 3

LOG3="$WORK/serial-exit-$MODE.log"
echo
echo "  Boot 3: deliberate program exit ($MODE)"
boot "$EXIT_ISO" "$LOG3"
show "program exit" "$LOG3"

echo "Assertions (program exit, $MODE):"
expect_present "Startup arg    : 2"          "the exit mode reached the program"    "$LOG3"
expect_present "Exit self-test"              "the program ran and chose to stop"    "$LOG3"
expect_present "exited with code 7"          "the code travelled back to the kernel" "$LOG3"
expect_present "nothing left to run"         "the kernel resumed as if called"      "$LOG3"
expect_absent  "PANIC"                       "no kernel panic"                      "$LOG3"
expect_absent  "program fault"               "ending normally is not a fault"       "$LOG3"

# ------------------------------------------------------------ run 4

LOG4="$WORK/serial-fpu-$MODE.log"
echo
echo "  Boot 4: floating point under interrupts ($MODE)"
boot "$FPU_ISO" "$LOG4"
show "floating point" "$LOG4"

echo "Assertions (floating point, $MODE):"
expect_present "Startup arg    : 3"          "the FPU mode reached the program"      "$LOG4"
expect_present "Floating point : x87 and SSE" "the kernel enabled SSE and x87"       "$LOG4"
expect_present "exact results : 0 wrong"     "no result was corrupted mid-calculation" "$LOG4"
expect_present "across a call : intact"      "state survived a system call"          "$LOG4"
expect_present "result        : PASS"        "the whole floating point check passed" "$LOG4"
expect_present "exited with code 0"          "the program finished normally"         "$LOG4"
expect_absent  "PANIC"                       "no kernel panic"                       "$LOG4"
expect_absent  "program fault"               "nothing faulted"                       "$LOG4"
# A #UD here would mean SSE was left disabled, and #NM would mean CR0.TS
# was left set. Both are reported as ordinary CPU exceptions, so the
# absence of the diagnostic is the assertion.
expect_absent  "CPU EXCEPTION"               "no exception from a vector instruction" "$LOG4"

# ------------------------------------------------------------ run 5

LOG5="$WORK/serial-spawn-$MODE.log"
echo
echo "  Boot 5: one program starts another ($MODE)"
boot "$SPAWN_ISO" "$LOG5"
show "spawn" "$LOG5"

echo "Assertions (spawn, $MODE):"
expect_present "Startup arg    : 5"          "the spawn mode reached the program"      "$LOG5"
expect_present "spawn: parent running"       "the parent ran"                          "$LOG5"
expect_present "spawn: child running"        "the child ran"                           "$LOG5"
expect_present "spawn: child returned 42"    "the child's exit code came back"         "$LOG5"
expect_present "exited with code 0"          "the parent finished normally after it"   "$LOG5"

# The claim.
#
# Three outcomes are refused here, not two. "No interrupt arrived while a
# program was in Ring 3" would satisfy "none landed in the wrong place"
# without the check having looked at anything, so the kernel reports it as
# its own outcome and the line below refuses it. Both sides spin for 60 ms
# at 100 Hz precisely so that this case cannot come up by accident.
expect_present "Stack check    : PASS"       "every Ring 3 interrupt landed on the running program's stack" "$LOG5"
expect_absent  "Stack check    : NO TICKS"   "and there were interrupts there to check"                  "$LOG5"
expect_absent  "landed off the running"      "none landed on a stack that was not the running one"       "$LOG5"

expect_absent  "PANIC"                       "no kernel panic"                         "$LOG5"
expect_absent  "program fault"               "neither program faulted"                 "$LOG5"
expect_absent  "CPU EXCEPTION"               "no CPU exception"                        "$LOG5"

echo
if [ "$FAILED" -eq 0 ]; then
    echo "  $CHECKS assertions run"
    echo "====> user program test PASSED ($MODE)"
    exit 0
else
    echo "  $CHECKS assertions run"
    echo "====> user program test FAILED ($MODE)"
    exit 1
fi
