#!/bin/bash
#
# Fault-injection test: the real proof that M1 works.
#
# Builds an image whose kernel command line asks for deliberate fault
# injection, boots it, and asserts that the exception handler produces a
# proper diagnostic. Before M1 this same fault would have been a triple
# fault and a silent reboot, with nothing on the wire to explain it.
#
# The image is built here rather than through the main Makefile so that the
# shipping image stays free of the fault-injection path. The xorriso
# options duplicate the Makefile's on purpose: this image only has to boot
# and fault, so a divergence there would be harmless, whereas adding a
# second configurable build path to the Makefile would not be.
#
# Usage: bash tools/run-fault-test.sh [bios|uefi]
#
set -u

PROJ="/mnt/c/FunnyOS"
cd "$PROJ"

BUILD_DIR="${FUNYOS_BUILD_DIR:-/var/tmp/funyos-build}"
WORK="$BUILD_DIR/fault-test"
MODE="${1:-bios}"
LIMINE_DIR="boot/limine/limine-binary"
VOLID="FUNNYOS"

ISO="$WORK/funyos-fault.iso"
LOG="$WORK/serial-$MODE.log"
TIMEOUT_SECS="${QEMU_TIMEOUT:-20}"

if [ ! -d "$BUILD_DIR/iso_root" ]; then
    echo "ERROR: $BUILD_DIR/iso_root missing; run make first." >&2
    exit 1
fi

# ---------------------------------------------------------------- image

rm -rf "$WORK"
mkdir -p "$WORK"
cp -r "$BUILD_DIR/iso_root" "$WORK/root"

cat > "$WORK/root/boot/limine.conf" <<'EOF'
# Generated by tools/run-fault-test.sh -- fault injection run.
timeout: 0
serial: yes
serial_baudrate: 115200

/FunnyOS (fault injection)
    protocol: limine
    kernel_path: fslabel(FUNNYOS):/boot/funyos.elf
    resolution: 1024x768x32
    cmdline: selftest=fault
EOF

echo "  Building fault-injection image..."
xorriso -as mkisofs -R -r -J \
    -V "$VOLID" \
    -b boot/limine-bios-cd.bin \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    --efi-boot boot/limine-uefi-cd.bin \
    -efi-boot-part --efi-boot-image \
    "$WORK/root" -o "$ISO" >/dev/null 2>&1

# ---------------------------------------------------------------- boot

rm -f "$LOG"

if [ -e /dev/kvm ] && [ -w /dev/kvm ]; then
    ACCEL="-enable-kvm -cpu host"
else
    ACCEL="-cpu max"
fi

if [ "$MODE" = "uefi" ]; then
    cp /usr/share/OVMF/OVMF_VARS_4M.fd "$WORK/vars.fd"
    FIRMWARE="-M q35 \
        -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,unit=1,file=$WORK/vars.fd"
    BOOT_ARGS=""
else
    FIRMWARE=""
    BOOT_ARGS="-boot d"
fi

echo "  Booting with fault injection ($MODE)..."

# shellcheck disable=SC2086
timeout "$TIMEOUT_SECS" qemu-system-x86_64 \
    -m 512 -cdrom "$ISO" $BOOT_ARGS \
    -serial "file:$LOG" -display none -no-reboot \
    $FIRMWARE $ACCEL >/dev/null 2>&1

echo
echo "=================== serial output ==================="
if [ -s "$LOG" ]; then
    sed -e 's/\x1b\[[0-9;]*[a-zA-Z]//g' "$LOG" | cat -s
else
    echo "(no serial output at all)"
fi
echo "====================================================="
echo

# ---------------------------------------------------------------- assert

FAILED=0
expect_present() {
    if grep -q "$1" "$LOG" 2>/dev/null; then
        printf '  [ok]   %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    fi
}

echo "Fault-injection assertions ($MODE path):"
expect_present "fault self-test"            "command line reached the kernel"
expect_present "CPU EXCEPTION"              "exception handler ran"
expect_present "#PF Page Fault"             "fault identified as a page fault"
expect_present "faulting address"           "CR2 reported"
expect_present "kernel mode"                "error code decoded"
expect_present "RIP        :"               "faulting instruction pointer reported"
expect_present "RFLAGS"                     "flags decoded"
expect_present "unhandled CPU exception 14" "handler reported and halted"
# The whole point: a fault must never escalate into a triple fault.
if grep -q "Boot verification PASSED" "$LOG" 2>/dev/null; then
    printf '  [ok]   %s\n' "boot completed before the fault"
else
    printf '  [FAIL] %s\n' "boot completed before the fault"
    FAILED=1
fi

echo
if [ "$FAILED" -eq 0 ]; then
    echo "====> fault-injection test PASSED ($MODE)"
    exit 0
else
    echo "====> fault-injection test FAILED ($MODE)"
    exit 1
fi
