#!/bin/bash
#
# User program test.
#
# Three boots of the same image, with the kernel command line as the only
# difference. Each one ends a process a different way, and each way has
# its own way of going wrong:
#
#   1. Normally. The shell starts in Ring 3 and stays there. Checks the
#      load path, the iretq into Ring 3, and the system call interface.
#
#   2. With `selftest=userfault`. The program writes to an address it has
#      no mapping for. This is the one that checks the claim FunnyOS
#      makes against DOS: a program that goes wrong stops being a
#      program, not a machine. The kernel must report the fault, end that
#      process and carry on -- not panic, and certainly not triple fault.
#
#   3. With `selftest=userexit`. The program returns a known non-zero
#      code. Checks the other way a process ends, and that the code
#      actually travels back rather than the kernel reporting whatever it
#      had to hand.
#
# Three boots rather than one because a process only ends once, and a
# single boot cannot show three different endings.
#
# Usage: bash tools/run-user-test.sh [ISO path] [bios|uefi]
#
set -u

PROJ="/mnt/c/FunnyOS"
cd "$PROJ"

BUILD_DIR="${FUNYOS_BUILD_DIR:-/var/tmp/funyos-build}"
ISO="${1:-$BUILD_DIR/funyos.iso}"
MODE="${2:-bios}"

WORK="$BUILD_DIR/user-test"
TIMEOUT_SECS="${QEMU_TIMEOUT:-20}"

FAILED=0

if [ ! -f "$ISO" ]; then
    echo "ERROR: ISO not found: $ISO" >&2
    echo "       Run make first." >&2
    exit 1
fi

if [ ! -d "$BUILD_DIR/iso_root" ]; then
    echo "ERROR: $BUILD_DIR/iso_root missing; run make first." >&2
    exit 1
fi

mkdir -p "$WORK"

if [ -e /dev/kvm ] && [ -w /dev/kvm ]; then
    ACCEL="-enable-kvm -cpu host"
    echo "  Acceleration : KVM (hardware)"
else
    ACCEL="-cpu max"
    echo "  Acceleration : TCG (software emulation, slow)"
fi

if [ "$MODE" = "uefi" ]; then
    cp /usr/share/OVMF/OVMF_VARS_4M.fd "$WORK/vars.fd"
    FIRMWARE_ARGS="-M q35 \
        -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,unit=1,file=$WORK/vars.fd"
    BOOT_ARGS=""
else
    FIRMWARE_ARGS=""
    BOOT_ARGS="-boot d"
fi

# ---------------------------------------------------------------- images
#
# Extra images with a different kernel command line, built here rather
# than through the Makefile for the same reason the fault-injection test
# does it: the shipping image should not carry paths that make a program
# fault or exit on its own.
build_image() {
    local cmdline="$1" output="$2"

    rm -rf "$WORK/root"
    cp -r "$BUILD_DIR/iso_root" "$WORK/root"

    cat > "$WORK/root/boot/limine.conf" <<EOF
# Generated by tools/run-user-test.sh -- $cmdline run.
timeout: 0
serial: yes
serial_baudrate: 115200

/FunnyOS ($cmdline)
    protocol: limine
    kernel_path: fslabel(FUNNYOS):/boot/funyos.elf
    resolution: 1024x768x32
    cmdline: $cmdline
EOF

    xorriso -as mkisofs -R -r -J \
        -V "FUNNYOS" \
        -b boot/limine-bios-cd.bin \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        --efi-boot boot/limine-uefi-cd.bin \
        -efi-boot-part --efi-boot-image \
        "$WORK/root" -o "$output" >/dev/null 2>&1
}

FAULT_ISO="$WORK/funyos-userfault.iso"
EXIT_ISO="$WORK/funyos-userexit.iso"

build_image "selftest=userfault" "$FAULT_ISO"
build_image "selftest=userexit"  "$EXIT_ISO"

# ---------------------------------------------------------------- boot

boot() {
    local image="$1" log="$2"
    rm -f "$log"

    # shellcheck disable=SC2086
    timeout "$TIMEOUT_SECS" qemu-system-x86_64 \
        -m 512 -cdrom "$image" $BOOT_ARGS \
        -serial "file:$log" -display none -no-reboot \
        $FIRMWARE_ARGS $ACCEL >/dev/null 2>&1
}

expect_present() {
    if grep -qF "$1" "$3" 2>/dev/null; then
        printf '  [ok]   %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    fi
}

expect_absent() {
    if grep -qF "$1" "$3" 2>/dev/null; then
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    else
        printf '  [ok]   %s\n' "$2"
    fi
}

show() {
    printf '\n=================== %s ===================\n' "$1"
    sed -n '/\[user program\]/,$p' "$2" 2>/dev/null | cat -s
    printf '=================================================\n\n'
}

# ------------------------------------------------------------ run 1

LOG1="$WORK/serial-normal-$MODE.log"
echo "  Boot 1: normal startup ($MODE)"
boot "$ISO" "$LOG1"
show "normal startup" "$LOG1"

echo "Assertions (normal startup, $MODE):"
expect_present "Image          :"            "user image embedded in the kernel" "$LOG1"
expect_present "FunnyCOM 0.1"                "shell started in Ring 3"           "$LOG1"
expect_present "F:\\>"                       "shell reached its prompt"          "$LOG1"
expect_absent  "PANIC"                       "no kernel panic"                   "$LOG1"
expect_absent  "program fault"               "the shell did not fault"           "$LOG1"
expect_absent  "CPU EXCEPTION"               "no CPU exception"                  "$LOG1"

# ------------------------------------------------------------ run 2

LOG2="$WORK/serial-fault-$MODE.log"
echo
echo "  Boot 2: deliberate program fault ($MODE)"
boot "$FAULT_ISO" "$LOG2"
show "program fault" "$LOG2"

echo "Assertions (program fault, $MODE):"
expect_present "Startup arg    : 1"          "the fault mode reached the program"        "$LOG2"
expect_present "program fault"               "kernel recognised the fault as a program's" "$LOG2"
expect_present "#PF Page Fault"              "fault identified as a page fault"          "$LOG2"
expect_present "faulting address"            "the faulting address was reported"         "$LOG2"
expect_present "ending the process"          "kernel said what it would do about it"     "$LOG2"
expect_present "killed by fault 14"          "process ended with the fault as its code"  "$LOG2"

# The claim being tested. A panic here would mean a program with a wild
# pointer takes the machine down -- exactly what DOS did, and exactly what
# this system exists to stop doing.
expect_absent  "PANIC"                       "the kernel did not panic"                  "$LOG2"
expect_absent  "CPU EXCEPTION"               "the fault was not treated as the kernel's" "$LOG2"
expect_present "nothing left to run"         "the kernel carried on after the program died" "$LOG2"

# ------------------------------------------------------------ run 3

LOG3="$WORK/serial-exit-$MODE.log"
echo
echo "  Boot 3: deliberate program exit ($MODE)"
boot "$EXIT_ISO" "$LOG3"
show "program exit" "$LOG3"

echo "Assertions (program exit, $MODE):"
expect_present "Startup arg    : 2"          "the exit mode reached the program"    "$LOG3"
expect_present "Exit self-test"              "the program ran and chose to stop"    "$LOG3"
expect_present "exited with code 7"          "the code travelled back to the kernel" "$LOG3"
expect_present "nothing left to run"         "the kernel resumed as if called"      "$LOG3"
expect_absent  "PANIC"                       "no kernel panic"                      "$LOG3"
expect_absent  "program fault"               "ending normally is not a fault"       "$LOG3"

echo
if [ "$FAILED" -eq 0 ]; then
    echo "====> user program test PASSED ($MODE)"
    exit 0
else
    echo "====> user program test FAILED ($MODE)"
    exit 1
fi
