#!/bin/bash
#
# The 8086 interpreter test.
#
# One boot of the same image, with `vm=1` on the kernel command line
# instead of the shell. What runs then is user/vm/: a Ring 3 program that
# builds the opcode dispatch table, runs two hand-assembled guest programs
# through the interpreter, and compares each terminal state against what
# the Intel manual says those instructions produce.
#
# Asserting is the point of this file. The terminal states are printed in
# full -- eight general registers, four segment registers, IP, and every
# flag by name -- but somebody reading a register dump is not a test, and
# something looked at once is not looked at again. So the verdict is also
# a line a script can read, and this is the script that reads it.
#
# `vm=1` rather than `selftest=`, because `selftest=` means "inject a
# fault on purpose" and this is not one: it is M3's deliverable, running.
#
# Usage: bash tools/run-vm-test.sh [ISO path] [bios|uefi]
#
set -u

BUILD_DIR="${FUNYOS_BUILD_DIR:-/var/tmp/funyos-build}"
ISO="${1:-$BUILD_DIR/funyos.iso}"
MODE="${2:-bios}"

WORK="$BUILD_DIR/vm-test"
TIMEOUT_SECS="${QEMU_TIMEOUT:-20}"

FAILED=0

if [ ! -f "$ISO" ]; then
    echo "ERROR: ISO not found: $ISO" >&2
    echo "       Run make first." >&2
    exit 1
fi

if [ ! -d "$BUILD_DIR/iso_root" ]; then
    echo "ERROR: $BUILD_DIR/iso_root missing; run make first." >&2
    exit 1
fi

mkdir -p "$WORK"

if [ -e /dev/kvm ] && [ -w /dev/kvm ]; then
    ACCEL="-enable-kvm -cpu host"
    echo "  Acceleration : KVM (hardware)"
else
    ACCEL="-cpu max"
    echo "  Acceleration : TCG (software emulation, slow)"
fi

if [ "$MODE" = "uefi" ]; then
    cp /usr/share/OVMF/OVMF_VARS_4M.fd "$WORK/vars.fd"
    FIRMWARE_ARGS="-M q35 \
        -drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,unit=1,file=$WORK/vars.fd"
    BOOT_ARGS=""
else
    FIRMWARE_ARGS=""
    BOOT_ARGS="-boot d"
fi

# ---------------------------------------------------------------- image
#
# An image with a different kernel command line, built here rather than
# through the Makefile, for the same reason the fault-injection and user
# tests do it: the shipping image should not start the interpreter
# instead of the shell.

build_image() {
    local cmdline="$1" output="$2"

    rm -rf "$WORK/root"
    cp -r "$BUILD_DIR/iso_root" "$WORK/root"

    cat > "$WORK/root/boot/limine.conf" <<EOF
# Generated by tools/run-vm-test.sh -- $cmdline run.
timeout: 0
serial: yes
serial_baudrate: 115200

/FunnyOS ($cmdline)
    protocol: limine
    kernel_path: fslabel(FUNNYOS):/boot/funyos.elf
    resolution: 1024x768x32
    cmdline: $cmdline
EOF

    xorriso -as mkisofs -R -r -J \
        -V "FUNNYOS" \
        -b boot/limine-bios-cd.bin \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        --efi-boot boot/limine-uefi-cd.bin \
        -efi-boot-part --efi-boot-image \
        "$WORK/root" -o "$output" >/dev/null 2>&1
}

VM_ISO="$WORK/funyos-vm.iso"
build_image "vm=1" "$VM_ISO"

# ---------------------------------------------------------------- boot

LOG="$WORK/serial-$MODE.log"

echo "  Boot: 8086 interpreter ($MODE)"
rm -f "$LOG"
timeout "$TIMEOUT_SECS" qemu-system-x86_64 \
    -m 512 -cdrom "$VM_ISO" $BOOT_ARGS \
    -serial "file:$LOG" -display none -no-reboot \
    $FIRMWARE_ARGS $ACCEL >/dev/null 2>&1

printf '\n=================== 8086 interpreter ===================\n'
sed -n '/\[vm86 interpreter\]/,$p' "$LOG" 2>/dev/null | cat -s
printf '=================================================\n\n'

expect_present() {
    if grep -qF "$1" "$LOG" 2>/dev/null; then
        printf '  [ok]   %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    fi
}

expect_absent() {
    if grep -qF "$1" "$LOG" 2>/dev/null; then
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    else
        printf '  [ok]   %s\n' "$2"
    fi
}

echo "Assertions ($MODE):"

# The dispatch table is merged before anything runs. A conflict here would
# make every result below meaningless, so it is asserted first.
expect_present "Startup arg    : 4"           "the vm mode reached the program"            "$LOG"
expect_present "built from the five group"    "the five opcode tables merged"              "$LOG"

# The guest that finishes. Its terminal state is compared instruction by
# instruction against the manual, so this line means more than "it ran".
expect_present "VM: case alu-loop: PASS"      "the finishing guest left the expected state" "$LOG"
expect_present "halted after"                 "and it got there by halting"                 "$LOG"

# The guest that must not run. An interpreter that fell through to the
# neighbouring encoding would execute this happily and print PASS for the
# case above while being wrong here.
expect_present "VM: case bad-opcode: PASS"    "the illegal encoding was refused"            "$LOG"
expect_present "vector 6 (invalid opcode)"    "refused as the invalid-opcode exception"     "$LOG"

# The interpreter's own verdict and the exit code it travelled back as.
expect_present "VM: RESULT PASS"              "the interpreter's own verdict"               "$LOG"
expect_present "exited with code 0"           "the verdict came back through the kernel"    "$LOG"

# The terminal state really was printed, which is the other half of the
# requirement -- an assertion nobody can read is hard to trust when it
# fails.
expect_present "flags  CF="                   "every flag was printed by name"              "$LOG"

# Things that must not have happened.
expect_absent  "CONFLICT"                     "no opcode is claimed twice"                  "$LOG"
expect_absent  "RUN LIMIT"                    "no guest ran away"                           "$LOG"
expect_absent  "PANIC"                        "no kernel panic"                             "$LOG"
expect_absent  "CPU EXCEPTION"                "no host exception"                           "$LOG"
expect_absent  "program fault"                "the process did not fault"                   "$LOG"

echo
if [ "$FAILED" -eq 0 ]; then
    echo "====> 8086 interpreter test PASSED ($MODE)"
    exit 0
else
    echo "====> 8086 interpreter test FAILED ($MODE)"
    exit 1
fi
