#!/bin/bash
#
# The screen test: what the machine draws, read back off the screen.
#
# Every other test in this tree reads the serial log, and the serial log
# cannot answer this question. A program's page being correct in its own
# memory, the kernel being handed it, the kernel saying where it put it --
# all of that is consistent with a framebuffer nobody ever wrote to. So
# this one boots a machine with a display, waits for a program to put its
# page up and hold it there, and takes a photograph of the result.
#
# The hold is what makes the photograph possible. The interpreter's
# self-test gives the screen back as soon as it is done, so there is no
# moment a screendump could be taken at; `vm=screen` runs the acceptance
# case and then waits for a key that this test never sends. The screen
# therefore does not change, and the capture can happen whenever this
# script gets around to it -- there is no sleep long enough or short
# enough to get right, because there is nothing to race.
#
# The pixels are judged by tools/check-screen-pixels.py, which locates the
# page from the serial log, measures the two colours off the screen rather
# than assuming a palette, and compares every scan line of every cell
# against the glyph the kernel's font gives for the character the guest
# left in its memory. What it does not check is in its own header.
#
# Usage: bash tools/run-screen-test.sh [ISO path]
#
set -u

BUILD_DIR="${FUNYOS_BUILD_DIR:-/var/tmp/funyos-build}"
ISO="${1:-$BUILD_DIR/funyos.iso}"

WORK="$BUILD_DIR/screen-test"

# Long enough for a boot, the acceptance case and the hold, with room for
# software emulation on a machine with no KVM. It is a guard against a
# hang rather than a schedule: the marker below is what the wait is really
# for, and this is what stops the wait when something is wrong.
TIMEOUT_SECS="${QEMU_TIMEOUT:-90}"
MARKER_WAIT="${SCREEN_MARKER_WAIT:-30}"

FAILED=0
CHECKS=0

if [ ! -f "$ISO" ]; then
    echo "ERROR: ISO not found: $ISO" >&2
    echo "       Run make first." >&2
    exit 1
fi

if [ ! -d "$BUILD_DIR/iso_root" ]; then
    echo "ERROR: $BUILD_DIR/iso_root missing; run make first." >&2
    exit 1
fi

mkdir -p "$WORK"

if [ -e /dev/kvm ] && [ -w /dev/kvm ]; then
    ACCEL="-enable-kvm -cpu host"
    echo "  Acceleration : KVM (hardware)"
else
    ACCEL="-cpu max"
    echo "  Acceleration : TCG (software emulation, slow)"
fi

FIRMWARE_ARGS=""
BOOT_ARGS="-boot d"

# ---------------------------------------------------------------- image
#
# An image whose kernel command line starts the interpreter in its "leave
# the page up" mode, built here rather than through the Makefile for the
# same reason the other tests do it: the shipping image should not start
# anything instead of the shell.

build_image() {
    local cmdline="$1" output="$2"

    rm -rf "$WORK/root"
    cp -r "$BUILD_DIR/iso_root" "$WORK/root"

    cat > "$WORK/root/boot/limine.conf" <<EOF
# Generated by tools/run-screen-test.sh -- $cmdline run.
timeout: 0
serial: yes
serial_baudrate: 115200

/FunnyOS ($cmdline)
    protocol: limine
    kernel_path: fslabel(FUNNYOS):/boot/funyos.elf
    resolution: 1024x768x32
    cmdline: $cmdline
EOF

    xorriso -as mkisofs -R -r -J \
        -V "FUNNYOS" \
        -b boot/limine-bios-cd.bin \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        --efi-boot boot/limine-uefi-cd.bin \
        -efi-boot-part --efi-boot-image \
        "$WORK/root" -o "$output" >/dev/null 2>&1
}

SCREEN_ISO="$WORK/funyos-screen.iso"
build_image "vm=screen" "$SCREEN_ISO"

# ---------------------------------------------------------------- capture

LOG="$WORK/serial.log"
PPM="$WORK/screen.ppm"

echo "  Boot: the acceptance case, held on screen"
rm -f "$LOG" "$PPM"

# The monitor is driven on stdin, so the command sequence has to be a
# process rather than a script: it waits for the marker in the serial log,
# waits one more second for the grid to be the last thing written, takes
# the screendump, and quits. The marker is what is being waited for -- the
# timeout around QEMU is only there so a machine that never reaches the
# hold still produces a log and a picture to judge.
(
    waited=0

    while [ "$waited" -lt "$((MARKER_WAIT * 5))" ]; do
        # Out of the wait as soon as the program has said how it went, one
        # way or the other. A run that fails never reaches the hold, and
        # sitting out the whole budget to photograph a screen the program
        # has already given back is thirty seconds of nothing in front of
        # a failure message.
        if grep -qF "the page stays up until a key arrives" "$LOG" 2>/dev/null
        then
            break
        fi

        if grep -qF "VM: RESULT" "$LOG" 2>/dev/null; then
            echo "  The interpreter finished without holding the page;" >&2
            echo "  capturing what it left." >&2
            break
        fi

        sleep 0.2
        waited=$((waited + 1))
    done

    if [ "$waited" -ge "$((MARKER_WAIT * 5))" ]; then
        echo "  The page never went up; capturing whatever is there." >&2
    fi

    sleep 1
    echo "screendump $PPM"
    sleep 2
    echo "quit"
) | timeout "$((TIMEOUT_SECS))" qemu-system-x86_64 \
    -m 512 -cdrom "$SCREEN_ISO" $BOOT_ARGS \
    -serial "file:$LOG" -display none -vga std -monitor stdio \
    -no-reboot $FIRMWARE_ARGS $ACCEL >/dev/null 2>&1

printf '\n=================== the screen ===================\n'
sed -n '/\[vm86 screen\]/,$p' "$LOG" 2>/dev/null | cat -s
printf '==================================================\n\n'

expect_present() {
    CHECKS=$((CHECKS + 1))
    if grep -qF "$1" "$LOG" 2>/dev/null; then
        printf '  [ok]   %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    fi
}

expect_absent() {
    CHECKS=$((CHECKS + 1))
    if grep -qF "$1" "$LOG" 2>/dev/null; then
        printf '  [FAIL] %s\n' "$2"
        FAILED=1
    else
        printf '  [ok]   %s\n' "$2"
    fi
}

echo "Assertions:"

# The program took the screen, and the machine had one to give.
expect_present "screen : the console screen is this program's" \
    "the interpreter took the console's screen"                       "$LOG"
expect_absent  "the console is NOT AVAILABLE" \
    "and the machine had one to give"                                 "$LOG"

# The guest ran, and its page is the one hello.asm's header describes.
expect_present "VM: case hello: PASS" \
    "the guest ran and left the page the manual says"                 "$LOG"

# What the page held, read by the interpreter out of the guest's own
# memory. This is the text the pixel check below will look for on the
# screen, so it is a fragment and not the whole padded row: the padding is
# as wide as the page and putting it here would be reproducing a constant
# from the kernel.
expect_present "screen : hello 80x25, row 0 = \"M4 hello from the BIOS" \
    "and row 0 of the page holds the guest's line"                    "$LOG"

# The count of pages is deliberately NOT asserted. It is one per slice in
# which the guest executed something, so it moves with the interpreter's
# slice size -- a number this test has no business knowing. What matters
# is that something was presented and that none of it was refused, and
# both of those are said in words.
expect_absent  "NOTHING WAS PRESENTED" \
    "the page was handed to the kernel"                               "$LOG"
expect_absent  "the kernel refused" \
    "and the kernel refused none of it"                               "$LOG"

# Where the kernel put it. This is the line the pixel check is anchored
# to, so it has to be there or nothing below can be judged.
expect_present "Screen         : a program has the screen, 80 columns at" \
    "the kernel said where the page went on the screen"               "$LOG"

# The hold, which is the only reason a photograph can be taken at all.
expect_present "screen : the page stays up until a key arrives" \
    "the page was left up for the capture"                            "$LOG"

expect_absent  "PANIC"            "no kernel panic"                   "$LOG"
expect_absent  "CPU EXCEPTION"    "no host exception"                 "$LOG"
expect_absent  "program fault"    "nothing faulted"                   "$LOG"

# ---- And then the pixels ---------------------------------------------

echo
echo "The framebuffer:"

# Counted with the rest. The checker does its own reporting and returns
# its own verdict, but it is an assertion this script made, and a summary
# that left it out would be a summary that undercounts what was run.
CHECKS=$((CHECKS + 1))

if [ ! -s "$PPM" ]; then
    echo "  [FAIL] no screendump was produced ($PPM)"
    FAILED=1
else
    python3 tools/check-screen-pixels.py \
        "$PPM" "$LOG" kernel/console/font8x16.c || FAILED=1
fi

echo
if [ "$FAILED" -eq 0 ]; then
    echo "  $CHECKS assertions run"
    echo "====> screen test PASSED"
    exit 0
else
    echo "  $CHECKS assertions run"
    echo "====> screen test FAILED"
    exit 1
fi
